<?php
/**
 * Admin Password Reset Script
 * Run this script from command line to securely change admin password
 * Usage: php reset_admin_password.php
 */

// Ensure this script is run from command line only
if (php_sapi_name() !== 'cli') {
    die("This script can only be run from command line for security reasons.\n");
}

echo "=== Light & Style Admin Password Reset ===\n\n";

// Get username
echo "Enter admin username (default: admin): ";
$username = trim(fgets(STDIN));
if (empty($username)) {
    $username = 'admin';
}

// Get new password
echo "Enter new password (minimum 8 characters): ";
$password = trim(fgets(STDIN));

// Validate password
if (strlen($password) < 8) {
    die("Password must be at least 8 characters long.\n");
}

// Confirm password
echo "Confirm new password: ";
$confirm_password = trim(fgets(STDIN));

if ($password !== $confirm_password) {
    die("Passwords do not match.\n");
}

// Store the password as plain text
$stored_password = $password;

echo "Choose storage method:\n";
echo "1. Update .env file (recommended)\n";
echo "2. Create config file\n";
echo "Enter choice (1 or 2): ";
$choice = trim(fgets(STDIN));

if ($choice === '1') {
    // Update .env file
    $env_file = __DIR__ . '/.env';
    
    if (file_exists($env_file)) {
        $env_content = file_get_contents($env_file);
        
        // Update existing values or add new ones
        if (strpos($env_content, 'ADMIN_USERNAME=') !== false) {
            $env_content = preg_replace('/ADMIN_USERNAME=.*/', 'ADMIN_USERNAME=' . $username, $env_content);
        } else {
            $env_content .= "\nADMIN_USERNAME=" . $username;
        }
        
        if (strpos($env_content, 'ADMIN_PASSWORD=') !== false) {
            $env_content = preg_replace('/ADMIN_PASSWORD=.*/', 'ADMIN_PASSWORD=' . $stored_password, $env_content);
        } else {
            $env_content .= "\nADMIN_PASSWORD=" . $stored_password;
        }
        
        if (file_put_contents($env_file, $env_content)) {
            echo "\n✅ Environment file updated successfully!\n";
            echo "Username: $username\n";
            echo "Password saved to: $env_file\n";
            
            // Set secure file permissions
            chmod($env_file, 0600);
            echo "- File permissions set to 600 (owner read/write only)\n";
        } else {
            echo "\n❌ Error: Could not update .env file.\n";
        }
    } else {
        // Create new .env file
        $env_content = "# Light & Style Admin Environment Configuration\n";
        $env_content .= "ADMIN_USERNAME=" . $username . "\n";
        $env_content .= "ADMIN_PASSWORD=" . $stored_password . "\n";
        
        if (file_put_contents($env_file, $env_content)) {
            echo "\n✅ Environment file created successfully!\n";
            echo "Username: $username\n";
            echo "Password saved to: $env_file\n";
            
            // Set secure file permissions
            chmod($env_file, 0600);
            echo "- File permissions set to 600 (owner read/write only)\n";
        } else {
            echo "\n❌ Error: Could not create .env file.\n";
        }
    }
} else {
    // Create config file (legacy method)
    $config_dir = __DIR__ . '/config';
    if (!file_exists($config_dir)) {
        mkdir($config_dir, 0755, true);
    }
    
    $config_file = $config_dir . '/admin_config.php';
    $config_content = "<?php\n";
    $config_content .= "// Secure admin credentials - Generated on " . date('Y-m-d H:i:s') . "\n";
    $config_content .= "// DO NOT edit this file manually\n";
    $config_content .= "\$custom_admin_credentials = [\n";
    $config_content .= "    '" . addslashes($username) . "' => '" . addslashes($stored_password) . "'\n";
    $config_content .= "];\n";
    $config_content .= "?>";
    
    if (file_put_contents($config_file, $config_content)) {
        echo "\n✅ Config file created successfully!\n";
        echo "Username: $username\n";
        echo "Password saved to: $config_file\n";
        
        // Set secure file permissions
        chmod($config_file, 0600);
        echo "- File permissions set to 600 (owner read/write only)\n";
    } else {
        echo "\n❌ Error: Could not write config file.\n";
    }
}

echo "\n🔒 Security notes:\n";
echo "- Keep credential files secure and not web-accessible\n";
echo "- Never commit .env files to version control\n";
echo "- Set appropriate file permissions\n";
echo "- Delete this script after use if no longer needed\n";

echo "\nDone.\n";
?>