<?php
// Secure admin credentials - Generated on 2025-10-10 18:54:09
// DO NOT edit this file manually
$custom_admin_credentials = [
    'admin' => '$2y$12$GITUeo7Dt4pmaLYkYtPStuVXf/4ifq8b04UpVHATuQyLLeQ./h7f2'
];
?>